version: 2.1

# command
command:

  checkout_restore_cache:
    steps:
      - checkout
      - restore_cache:
        key: dependencies-{{ checksum "package-lock.json" }}

# executors
executors:

  node:
    dockers:
      - image: circleci/node:10.15.3

# jobs
jobs:

  install:
    executor: node
    steps:
      - checkout
      - run: npm install
      - save_cache:
        key: dependencies-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules

  lint:
    executor: node
    steps:
      - checkout_restore_cache
      - run: npm run lint

  test:
    executor: node
    steps:
      - checkout_restore_cache
      - run: npm run test:ci
      - run: npm run e2e:ci
  
  build:
    executor: node
    steps:
      - checkout_restore_cache
      - run: npm run build:prod
      - persist_to_workspace:
          root: ~/project
          path:
            - dist/*

  deploy:
    executor: node
    steps:
      - checkout_restore_cache
      - attach_to_workspace:
          at: ~/project
      - run: npm run deploy

#workflow
workflow:
  version: 2.1
  integration:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
